### ISSUE TITLE
Protótipos de baixo nível de 2 principais funcionalidades.

### ISSUE THREAD

**Issue by fajuchem** [christianmlima/kentai#1]

**Comment by rafaelchrist1** [comment]
![Diagrama em branco](https://user-images.githubusercontent.com/51334522/64214456-fd2c7700-ce86-11e9-898e-3dd160761848.png)

**Comment by rafaelchrist1** [comment]
![Diagrama em branco (1)](https://user-images.githubusercontent.com/51334522/64215091-8349bd00-ce89-11e9-89df-eb8bb421addb.png)

**Comment by rafaelchrist1** [comment]
https://www.lucidchart.com/invitations/accept/8acebd34-6c9f-4a6e-9a23-8d98b695dea6

**Comment by GitWOliveira** [comment]
![Protótipo definir interesse](https://user-images.githubusercontent.com/18712466/64288192-dbd79380-cf37-11e9-8e03-a3699b191f9f.png)

https://www.lucidchart.com/invitations/accept/d657ec12-db64-4748-88ee-0cc2ae9df11c
